package com.zoltraak.gateway.domain.enums;

public enum GatewayErrorCode {
    BAD_REQUEST,
    STORY_FAILED,
    INVALID_TOKEN,
    TOKEN_EXPIRED,
    QUEUE_TIMEOUT,
    WARMUP_TIMEOUT,
    INTERNAL_ERROR,
    IMAGE_GEN_FAILED,
    POD_START_FAILED,
    INTENT_UNRESOLVED,
    NETWORK_UNREACHABLE,
    PROVIDER_UNAVAILABLE
}
