services:
  zoltraak-gateway:
    image: ghcr.io/sudosf/zoltraak-gateway:dev
    container_name: zoltraak-gateway-dev
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - RUNPOD_API_KEY_DEV=${RUNPOD_API_KEY_DEV}
      - OPEN_WEB_UI_API_KEY=${OPEN_WEB_UI_API_KEY}
      - VAST_AI_API_KEY_DEV=${VAST_AI_API_KEY_DEV}
    restart: unless-stopped