services:
  zoltraak-gateway:
    image: ghcr.io/sudosf/zoltraak-gateway:latest
    container_name: zoltraak-gateway
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - .env
    restart: unless-stopped
    stop_grace_period: 35s