services:
  zoltraak-gateway:
    image: ghcr.io/sudosf/zoltraak-gateway:dev
    container_name: zoltraak-gateway-dev
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - ACTIVE_PROVIDER=${ACTIVE_PROVIDER}
      - GATEWAY_API_KEY=${GATEWAY_API_KEY}
      - RUNPOD_API_KEY_DEV=${RUNPOD_API_KEY_DEV}
      - VAST_AI_API_KEY_DEV=${VAST_AI_API_KEY_DEV}
      - IDLE_CHECK_TIMEOUT_MINUTES=${IDLE_CHECK_TIMEOUT_MINUTES}
    restart: unless-stopped