name: Qodana
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2026.1
        with:
          pr-mode: false
          cache-default-branch-only: true
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_1806812611 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'
          
