name: Release

on:
  push:
    branches:
      - master
      - prod

jobs:
  dev-build:
    if: github.ref_name == 'master'
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/sudosf/zoltraak-gateway:dev

  prod-build-and-release:
    if: github.ref_name == 'prod'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'corretto'
          cache: maven

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: ghcr.io/sudosf/zoltraak-gateway:candidate

      - name: Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/exec
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          docker tag ghcr.io/sudosf/zoltraak-gateway:candidate ghcr.io/sudosf/zoltraak-gateway:latest
          docker tag ghcr.io/sudosf/zoltraak-gateway:candidate ghcr.io/sudosf/zoltraak-gateway:${{ steps.semantic.outputs.new_release_version }}
          docker push ghcr.io/sudosf/zoltraak-gateway:latest
          docker push ghcr.io/sudosf/zoltraak-gateway:${{ steps.semantic.outputs.new_release_version }}